### ISSUE TITLE
Writing headers late causes a crash

### ISSUE THREAD

**Issue by GeorgeLyon** [swift-server/http#100]
The following code causes a crash at the specified line because `parsedHTTPVersion` is nil
```
try! server.start(port: port) { req, resp in
            DispatchQueue.main.async {
                resp.writeHeader(status: .ok)
                resp.done()
            }
            return .discardBody
}
```
https://github.com/swift-server/http/blob/825b680c64c058371f90f1f2308405ed506190ab/Sources/HTTP/HTTPStreamingParser.swift#L401

It seems `.discardBody` causes `resp.done()` to be called, although writing a response after the request has been processed seems like a use case that should be supported.

**Comment by helje5** [comment]
The current implementation is synchronous, not async. You can't leave the scope of the handler.

You can try my async fork:

    https://github.com/ZeeZide/http/tree/feature/gcd-async-server

and see whether it works for you. Note that your example still needs to be adjusted:

```
try! server.start(port: port) { req, resp, q in
  DispatchQueue.main.async {
    // do something
    q.async {
      resp.writeHeader(status: .ok)
       resp.done()
    }
  }
  return .discardBody
}
```

(i.e. you can dispatch to other queues as you like, but you need to dispatch back to the queue passed into the handler when calling the API).

**Comment by GeorgeLyon** [comment]
Ah, I had a feeling this was just an "it is too early" thing.

Out of curiosity, why do you need to async to a particular queue? As far as I can tell, it only matters that writes on a socket are synchronous with regard to each other, and even if there is book-keeping that needs to be done on `done()` that can be async-ed under the hood.

**Comment by helje5** [comment]
> Out of curiosity, why do you need to async to a particular queue?

It is an optimisation. Consider it the 'main queue' of the handler. If the API calls can be done from arbitrary queues, the API itself always has to synchronise the calls. That is more convenient to the user, but leads to a LOT of (often unnecessary, essentially for pretty much any write call) async queue dispatches within the API, which this thing avoids.
I posted some message on the mailing list discussing the available options. You may want to respond to this.

> As far as I can tell, it only matters that writes on a socket are synchronous with regard to each other, and even if there is book-keeping that needs to be done on done() that can be async-ed under the hood.

Hm, maybe I'm actually wrong on this one. You are right, what you try to do could still work w/ a synchronous API. I guess I assume that the current API works a little like my Apache implementation, and in this, the processing needs to have finished when leaving the handler scope.
