### ISSUE TITLE
How to install it?

### ISSUE THREAD

**Issue by sukhrobkhakimov** [swift-server/http#105]
No instructions about installation are provided. I can't install it via Swift Package Manager.

**Comment by helje5** [comment]
No instructions are required, this works like any other SPM package. (if you have specific errors, please open a more detailed issue!)

I wrote up a small step-by-step tutorial on how to use it: [Using the Swift Server API 0.1.0](http://www.alwaysrightinstitute.com/http-010/), maybe that helps you get going.

**Comment by sukhrobkhakimov** [comment]
Thanks a lot

**Comment by fbukevin** [comment]
@helje5 Helpful!
