### ISSUE TITLE
Swift 4 support

### ISSUE THREAD

**Issue by carlbrown** [swift-server/http#40]
I started Swift 4 support (https://github.com/carlbrown/http/tree/swift4), but got blocked on #22. It doesn't look like that's going to get fixed, so I'll work around it, starting with #39 

Once that gets merged, I'll push a new swift-tools-version = 4.0 `Package.swift` file and associated fixes to either `develop` or a swift4 specific branch, whichever we think makes the most sense.

**Comment by seabaylea** [comment]
This has been done, so I'll close this one off.
