### ISSUE TITLE
API uses POSIXError

### ISSUE THREAD

**Issue by helje5** [swift-server/http#8]
The code uses `POSIXError` which I think is not an actual thing an implementation can create, right? It is just a namespace (at least on macOS, maybe that is different on Linux?).

Is that meant to be `POSIXErrorCode`?

https://github.com/swift-server/http/blob/develop/Sources/SwiftServerHttp/HTTPCommon.swift#L72

Note: This is reported as an Issue, because the error part of the API cannot be implemented. (My suggestion would be to not expose 'POSIX' at all but instead use an own HTTPError type which wraps the underlying socket error)

**Comment by tanner0101** [comment]
I agree. Mentioning POSIX at all seems like an implementation detail.

**Comment by carlbrown** [comment]
This was removed/fixed in #19
